- type: job
  id: Outlaw
  name: job-name-outlaw
  description: job-description-outlaw
  playTimeTracker: JobOutlaw
  requirements: # once again we dont really use roletimers cause its a private server but if anyone wants to fork this role for whatever reason...
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 #20 hours
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 72000 #20 hours
    - !type:OverallPlaytimeRequirement
      time: 144000 #40 hrs
  startingGear: OutlawGear
  icon: "JobIconOutlaw"
  supervisors: job-supervisors-cencomonly
  canBeAntag: false # basically already a less malicious antag? also syndi + outlaw = overpowered
  goobcoins: 30 #Goob content
  access:
  - Hydroponics # so they can grow illegal substances
  - Cargo
  - Maintenance
  - Salvage
  - External

- type: startingGear
  id: OutlawGear
  equipment:
    id: OutlawPDA
    ears: ClothingHeadsetCargo
    belt: ClothingBeltAssaultOutlawFilled
  storage:
    back:
    - Flash
  inhand:
  - BaseOutlawRadio